export const AUTH_START = 'AUTH_START';
export const AUTHENTICATION = 'AUTHENTICATION';
export const AUTH_FAILED = 'AUTH_FAILED';
export const SIGN_OUT = 'SIGN_OUT';

export const SET_PROFILE = 'SET_PROFILE';

export const FETCH_DATA = 'FETCH_DATA';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

export const SET_MONTHLY_BUDGET = 'SET_MONTHLY_BUDGET';

export const ADD_SAVED_TRANSACTION = 'ADD_SAVED_TRANSACTION';
export const DELETE_SAVED_TRANSACTION = 'DELETE_SAVED_TRANSACTION';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CREATE_PERSONAL_LIST = 'CREATE_PERSONAL_LIST';
export const DELETE_PERSONAL_LIST = 'DELETE_PERSONAL_LIST';
