export const AUTH_START = 'AUTH_START';
export const AUTHENTICATION = 'AUTHENTICATION';
export const AUTH_FAILED = 'AUTH_FAILED';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_DATA = 'FETCH_DATA';

export const ADD_LIST = 'ADD_LIST';
export const SELECT_LIST = 'SELECT_LIST';
export const DELETE_LIST = 'DELETE_LIST';

export const SET_EXPENSES = 'SET_EXPENSES';
export const ADD_EXPENSES = 'ADD_EXPENSES';
export const SELECT_EXPENSES = 'SELECT_EXPENSES';
export const UPDATE_EXPENSE_PENDING_AMOUNT = 'UPDATE_EXPENSE_PENDING_AMOUNT';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const SET_FILTERS = 'SET_FILTERS';
